sudo: false

language: node_js

node_js:
  - '9.0'
  - '10.0'

after_script:
 - npm run coveralls

after_failure:
 - tar -cjf "shortbread-meta_travis_${TRAVIS_BUILD_NUMBER}.tar.bz2" tmp && curl --ftp-create-dirs -T "shortbread-meta_travis_${TRAVIS_BUILD_NUMBER}.tar.bz2" -u $FTP_USER:$FTP_PASSWORD "ftp://jkphl.is/${TRAVIS_REPO_SLUG}/shortbread-meta_travis_${TRAVIS_BUILD_NUMBER}.tar.bz2"

matrix:
  fast_finish: true
